/**
 * @description Generated by FTL Stack CLI: Entry point of the application. Edit
 * this file as necessary or replace the contents entirely.
 */

// Core & third-party imports
import React from 'react';
import { createRoot } from 'react-dom/client';

// Create react app and mount to DOM
const container = document.getElementById('app')!;
createRoot(container).render(
  <React.StrictMode>
    <FlakRouter />
  </React.StrictMode>
);
