/**
 * @author SaiForceOne
 * @description functionality related to building index page components for the
 * frontend of a STRM Stack project
 */

// STRM Stack Imports
import FrontendOpt = STRMStackCLI.FrontendOpt;
import { LocaleManager } from '../localeManager.js';
import { getStandardImports } from './feHelperUtils.js';
import STRMController = STRMStackCLI.STRMController;

// Helpers

/**
 * @function getIndexBuilder
 * @description Returns the appropriate index page builder which when run, returns
 * a string representation of the page component which can then be written to the
 * filesystem
 * @param {FrontendOpt} frontendOpt specifies the frontend to generate the page for
 * @param {string} componentName the name of the frontend component
 * @param {string} componentPath the relative component path independent of frontend
 * @param {string} controller the related controller
 * @returns {() => string}
 * */
function getIndexBuilder(
  frontendOpt: FrontendOpt,
  componentName: string,
  componentPath: string,
  controller: STRMController
): () => string {
  const localeData = LocaleManager.getInstance().getLocaleData();
  const INDEX_BUILDERS: Record<FrontendOpt, () => string> = {
    lit: () => 'lit template placeholder', // todo: implement this
    vue: () => {
      return `<script lang="ts">
// Generated by the ST🌀RM Stack ${new Date().toLocaleDateString()}
// core imports
import {defineComponent} from 'vue';


export default defineComponent({
  computed: {
    /**
     * Developer Note: you should remove these computed properties since you probably won't really need them
     */
    pageTitle: () => 'ST🌀RM Stack',
    techIconSize: () => 2.25,
    contactIconSize: () => 1.5,
    commonSpanStyle() {
      return "px-1 py-0.5 bg-strm-bg-dark rounded italic text-white font-bold";
    },
    commonSummaryStyle() {
      return "font-medium text-slate-600 cursor-pointer";
    },
    commonDetailStyle() {
      return "border-slate-400 border-2 rounded p-2 mb-2";
    },
    commonHeadingL3() {
      return "font-heading text-lg font-medium";
    }
    // - END of styles to be removed -
  },
  name: '${componentName}',
});
</script>

<template>
  <div class="w-full min-h-screen flex flex-col p-2">
    <div class="min-h-full mx-auto w-full md:w-3/5 md:self-center">
      <header class="mb-4 text-center">
        <h1 class="text-4xl font-heading text-strm-bg-dark">${componentName} Index Page</h1>
        <p class="text-lg italic text-slate-700">Autogenerated by the ST🌀RM Stack</p>
      </header>
      <div class="text-center">
        <h2 class="text-2xl font-bold font-heading">What to do next</h2>
        <p class="text-lg">Now that you have generated a new module and have this placeholder component, here are things
          you should do next</p>
      </div>
      <section class="mt-4">
        <h3 :class="commonHeadingL3">Component Details</h3>
        <div class="p-1">
          <details :class="commonDetailStyle">
            <summary :class="commonSummaryStyle">Component Details</summary>
            <div class="table w-full">
              <div class="table-header-group">
                <div class="table-row">
                  <div class="table-cell text-left">Component</div>
                  <div class="table-cell text-left">Detail</div>
                </div>
              </div>
              <div class="table-row-group">
                <div class="table-row">
                  <div class="table-cell">Module Name</div>
                  <div class="table-cell"><span :class="commonSpanStyle">${
                    componentPath.split('/')[0]
                  }</span></div>
                </div>
                <div class="table-row">
                  <div class="table-cell">API endpoint</div>
                  <div class="table-cell"><span :class="commonSpanStyle">api/${
                    controller.endpointBase
                  }</span></div>
                </div>
              </div>
            </div>
          </details>
        </div>
      </section>
      <section class="mt-4">
        <h3 :class="commonHeadingL3">Frontend</h3>
        <div class="p-1">
          <details :class="commonDetailStyle">
            <summary :class="commonSummaryStyle">Edit this component</summary>
            <p class="text-lg">
              <span :class="commonSpanStyle">1.</span> Edit this component in <span :class="commonSpanStyle">strm_fe_vue/src/pages/${componentPath}.vue</span>
            </p>
          </details>
        </div>
      </section>
      <section class="mt-4">
        <h3 :class="commonHeadingL3">Backend</h3>
        <div class="">
          <details :class="commonDetailStyle">
            <summary :class="commonSummaryStyle">Edit the model</summary>
            <p class="text-lg">
              <span :class="commonSpanStyle">1.</span> Edit the corresponding model file in <span
                :class="commonSpanStyle">strm_models/${
                  controller.modelName
                }</span>
            </p>
          </details>
        </div>
        <div class="">
          <details :class="commonDetailStyle">
            <summary :class="commonSummaryStyle">Edit the Controller</summary>
            <p class="text-lg">
              <span :class="commonSpanStyle">1.</span> Edit the corresponding controller file in <span
                :class="commonSpanStyle">strm_controllers/${
                  controller.controllerName
                }.py</span>
            </p>
          </details>
        </div>
      </section>
    </div>
    <footer
      class="mt-4 p-2 text-slate-600 flex flex-col items-center absolute bottom-0 left-0 right-0"
      id="strm-footer"
    >
      <p class="text-lg">Need help or have questions?</p>
      <div class="w-full md:w-3/5 grid grid-cols-2 gap-2">
        <div>
          <a
            class="flex items-center gap-x-1"
            href="https://discord.gg/sY3a5VN3y9"
            title="Link to the Peanut Cart Express Discord"
            target="_blank"
          >
            <v-icon name="si-discord" :scale="contactIconSize"/>
            P.C.E Discord
          </a>
        </div>
        <div class="flex">
          <a
            class="flex items-center gap-x-1"
            title="Link to the STORM Stack on Github"
            href="https://github.com/saiforceone/strm-cli"
            target="_blank"
          >
            <v-icon name="si-github" :scale="contactIconSize"/>
            {{ pageTitle }} Stack Github
          </a>
        </div>
      </div>
    </footer>
  </div>
</template>
      `;
    },
    react: () => {
      return `// Generated by the ${
        localeData.misc.STORM_BRANDED
      } ${new Date().toLocaleDateString()}
// core imports
${getStandardImports(frontendOpt)}

/**
 * @function Index
 * @description Autogenerated index page component for ${componentName}
 */
function Index(): React.ReactElement {
  return (
    <div className="p-2">
      <h1 className="text-4xl font-heading">${componentName} Index Page</h1>
      <p>Autogenerated by the ${localeData.misc.STORM_BRANDED}</p>
      <h2 className="text-2xl font-bold font-heading">What to do next</h2>
      <ul>
        <li>edit the corresponding model file in <b>strm_models/${componentName.toLowerCase()}.py</b></li>
        <li>edit the corresponding controller file in <b>strm_controllers/${componentName.toLowerCase()}_controller.py</b></li>
      </ul>
    </div>
  );
}
 
export default Index;
`;
    },
  };

  return INDEX_BUILDERS[frontendOpt];
}

/**
 * @function generateIndexPage
 * @description Given a frontend option specified by frontendOpt, generates an
 * index page (starter) specific to the frontend option with instructions on
 * what to do next as a string to be written to the filesystem by another function.
 * @param {FrontendOpt} frontendOpt frontend option that determines which index
 * page 'template' should be used
 * @param {string} componentName The name of the component
 * @param {string} componentPath The relative path of the component
 * @param {STRMController} controller The related controller
 * @returns {string} the page component as a string
 */
export function generateIndexPage(
  frontendOpt: FrontendOpt,
  componentName: string,
  componentPath: string,
  controller: STRMController
): string {
  return getIndexBuilder(
    frontendOpt,
    componentName,
    componentPath,
    controller
  )();
}
