/**
 * @author SaiForceOne
 * @description functionality related to building details page components for the
 * frontend of a STRM Stack project
 */

// STRM Stack Imports
import FrontendOpt = STRMStackCLI.FrontendOpt;
import { LocaleManager } from '../localeManager.js';

function getDetailsBuilder(
  frontendOpt: FrontendOpt,
  componentName: string,
  componentPath: string,
  controllerName: string
): () => string {
  const localeData = LocaleManager.getInstance().getLocaleData();
  const execTime = new Date();
  const DETAIL_BUILDERS: Record<FrontendOpt, () => string> = {
    react: () => {
      return `// Generated by the ${
        localeData.misc.STORM_BRANDED
      } ${execTime.toLocaleDateString()}
// Core imports
import React from 'react';


/**
 * @function ${componentName}
 * @description Renders the page for ${componentName}
 * @constructor
 * @returns {React.ReactElement}
 */
function ${componentName}(): React.ReactElement {
  return (
    <div className="p-2">
      <h1>${componentName} Details</h1>
      <p>Autogenerated by the ST🌀RM Stack</p>
      <h2 className="text-2xl font-bold font-heading">What to do next</h2>
      <ul>
        <li>edit the edit this page <b>strm_fe_${frontendOpt}/src/pages/${componentPath}.tsx</b> to match your design</li>
        <li>edit the corresponding controller file in <b>strm_controllers/${controllerName}.py</b> to include
          functionality to load this resource
        </li>
      </ul>
    </div>
  );
}

export default ${componentName};
`;
    },
    lit: () => '',
    vue: () => '',
  };

  return DETAIL_BUILDERS[frontendOpt];
}

function generateDetailsPage(
  frontendOpt: FrontendOpt,
  componentName: string,
  componentPath: string,
  controllerName: string
): string {
  return getDetailsBuilder(
    frontendOpt,
    componentName,
    componentPath,
    controllerName
  )();
}

export default generateDetailsPage;
