# Create-Storm-Stack code quality and enforcement workflow
name: quality-checks
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  format-code:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install deps
        run: npm install

      - name: Run Prettier Check
        run: npm run prettier:check

      - name: Lint Source Files
        run: npm run lint
